export { default as dashboardLoader } from './dashboard.loader'
export { default as jobsLoader } from './jobs.loader'
export { default as editJobLoader } from './editjob.loader'
export { default as adminLoader } from './admin.loader'
export { default as statsLoader } from './stats.loader'
