export { default as HomeLayout } from './Home/HomeLayout'
export { default as DashboardLayout } from './Dashboard/DashboardLayout'
export { default as AllJobs } from './Dashboard/AllJobs'
export { default as AddJob } from './Dashboard/AddJob'
export { default as Admin } from './Dashboard/Admin'
export { default as DeleteJob } from './Dashboard/DeleteJob'
export { default as EditJob } from './Dashboard/EditJob'
export { default as Error } from './Error/Error'
export { default as Landing } from './Home/Landing'
export { default as Login } from './Auth/Login'
export { default as Profile } from './Dashboard/Profile'
export { default as Register } from './Auth/Register'
export { default as Stats } from './Dashboard/Stats'

// exports all page components from this one file
